/**
 * "for ___" lines displayed on the landing page.
 * 150 are randomly selected on each page load.
 */

const FOR_LINES: string[] = [
	// ── originals ──
	"for you",
	"for me",
	"for non-writers",
	"for jotters",
	"for scribblers",
	"for dreamers",
	"for thinkers",
	"for overthinkers",
	"for the sleepless",
	"for the restless",
	"for people who journal but won't call it that",
	"for letter-writers",
	"for love-letter-writers",
	"for apology-drafters",
	"for the unsent message",
	"for 3am thoughts",
	"for shower arguments",
	"for the thing you'll forget by morning",
	"for armchair philosophers",
	"for actual armchair owners",
	"for aspiring novelists",
	"for people on chapter one for three years",
	"for former bloggers",
	"for people who miss blogspot",
	"for reply guys",
	"for the chronically online",
	"for the intentionally offline",
	"for the waiting room",
	"for the back of the lecture hall",
	"for lunch breaks",
	"for early risers",
	"for the caffeinated",
	"for the decaf curious",
	"for people who sing in the car",
	"for cooks who don't use recipes",
	"for people between things",
	"for the employed",
	"for the unemployed",
	"for the funemployed",
	"for extroverts who need to process",
	"for the spiritual but not religious",
	"for the religious but not spiritual",
	"for the confused",
	"for the certain",
	"for the temporarily certain",
	"for adults who feel like kids",
	"for your future self",
	"for your past self",
	"for the version of you that almost existed",
	"for complaints never filed",
	"for gratitude never expressed",
	"for the epiphany on the subway",
	"for the thing you overheard at the coffee shop",
	"for manifestos",
	"for grocery lists that became poems",
	"for poems that became grocery lists",
	"for the marginalia",
	"for the footnotes",
	"for the PS at the end",
	"for ghost stories",
	"for origin stories",
	"for the story you keep telling differently",
	"for conspiracies",
	"for confessions",
	"for the truth",
	"for the almost truth",
	"for the beautiful lie",
	"for people who can't afford therapists",
	"for people who are their own therapist",
	"for people who run from things",
	"for people who run toward things",
	"for people who talk to their plants",
	"for middle children especially",
	"for descendants who haven't been born",
	"for the eulogy you hope someone writes",
	"for the toast at the wedding",
	"for the speech you gave in the mirror",
	"for vows",
	"for broken vows",
	"for renewed vows",
	"for new year's resolutions",
	"for february",
	"for the long weekend",
	"for the Sunday scaries",
	"for Monday mornings",
	"for Friday at 4:58pm",
	"for the gap year",
	"for the lost decade",
	"for the comeback",
	"for rough drafts",
	"for final drafts",
	"for drafts that are never final",
	"for the delete key",
	"for the undo button",
	"for the things you can't undo",
	"for permanence",
	"for impermanence",
	"for the space between",
	"for no one",
	"for everyone",
	"for public",
	"for private",

	// ── writing-adjacent, kinda silly ──
	"for people who say they don't write but have 400 notes on their phone",
	"for people who wrote one poem in 2019 and still think about it",
	"for people whose journal is just apologies to their journal for not writing",
	"for people who buy notebooks like they buy lottery tickets",
	"for people who start every entry with 'so'",
	"for people who start every entry with 'anyway'",
	"for people who write 'I should write more' and then close the notebook",
	"for people who type faster than they think",
	"for people who think faster than they type",
	"for people who wrote a novel in their head on the drive home",
	"for people who open a blank doc and then check their email",
	"for people who call it 'content' when they mean 'writing'",
	"for people who have a 'writing playlist' but never write to it",
	"for people whose drafts folder is a graveyard",
	"for people who text in paragraphs",
	"for people who leave voice notes that are basically essays",
	"for people who outline the outline",
	"for people who say 'I'll just jot this down' and write three pages",
	"for people who rewrite the same sentence eleven times and go back to the first one",
	"for people who delete everything and start with 'anyway'",
	"for people who write letters they'll never send and feel better anyway",
	"for people who narrate their life in their head",
	"for people who rehearse conversations in the shower and forget the good parts",
	"for people who have strong opinions about em dashes",
	"for people who screenshot quotes instead of bookmarking them",
	"for people who say 'I'm not a writer' and then write something beautiful",

	// ── writing & words ──
	"for the first sentence",
	"for the last sentence",
	"for the sentence you keep rewriting",
	"for paragraphs that won't end",
	"for one-word paragraphs",
	"for words you had to look up",
	"for words you made up",
	"for the word on the tip of your tongue",
	"for typos you left on purpose",
	"for autocorrect disasters",
	"for strikethrough text",
	"for bold text",
	"for italic feelings",
	"for ellipses…",
	"for em dashes—",
	"for semicolons; used correctly",
	"for the Oxford comma debate",
	"for run-on sentences that just keep going because you have so much to say",
	"for sentence fragments",
	"for the paragraph break that changes everything",
	"for writing in all caps",
	"for whispering in lowercase",
	"for margins full of notes",
	"for crossed-out words",
	"for words you circled twice",
	"for the right word",
	"for the almost-right word",
	"for people who write in pen",
	"for people who only write in pencil",
	"for the smudge on the left-hander's palm",
	"for cursive",
	"for print",
	"for handwriting no one can read",
	"for handwriting that's almost calligraphy",
	"for the blank page",
	"for the fear of the blank page",
	"for the excitement of the blank page",
	"for page one",
	"for page two hundred",
	"for the page you ripped out",
	"for the page you taped back in",
	"for notebooks you never finished",
	"for notebooks you never started",
	"for the notebook you carry everywhere",
	"for the notebook that's too nice to write in",
	"for loose-leaf paper",
	"for napkin sketches",
	"for receipts with ideas on the back",
	"for margins of textbooks",
	"for Post-it notes",
	"for sticky notes on the monitor",
	"for notes-to-self",
	"for reminders you ignored",
	"for to-do lists that became wishlists",
	"for wishlists that became plans",
	"for plans that became memories",
	"for prologues",
	"for epilogues",
	"for the chapter you skipped",
	"for the chapter you reread",
	"for the book you never finished reading",
	"for the book you finished in one sitting",

	// ── time & moments ──
	"for 4am clarity",
	"for 2pm drowsiness",
	"for the golden hour",
	"for the blue hour",
	"for the hour before dawn",
	"for the minute after midnight",
	"for time zones",
	"for jet lag thoughts",
	"for the layover",
	"for delayed flights",
	"for train windows",
	"for bus rides",
	"for backseat daydreams",
	"for red lights",
	"for the walk home",
	"for the long way around",
	"for shortcuts",
	"for detours",
	"for the scenic route",
	"for rainy days",
	"for snow days",
	"for the first warm day",
	"for the last day of summer",
	"for autumn leaves",
	"for spring cleaning",
	"for winter silence",
	"for the solstice",
	"for the equinox",
	"for eclipses",
	"for full moons",
	"for new moons",
	"for starless nights",
	"for cloudless skies",
	"for overcast afternoons",
	"for fog",
	"for the eye of the storm",
	"for the calm after",
	"for Tuesdays",
	"for Wednesdays especially",
	"for Thursday at 11pm",
	"for Saturday mornings",
	"for Sunday evenings",
	"for birthdays",
	"for the day after your birthday",
	"for anniversaries you forgot",
	"for anniversaries no one else remembers",
	"for the in-between days",
	"for the day nothing happened",
	"for the day everything changed",
	"for the longest day of the year",
	"for the shortest",
	"for leap years",
	"for the extra second",

	// ── people & relationships ──
	"for former best friends",
	"for the friend you lost touch with",
	"for the friend who texts back immediately",
	"for the friend who never texts back",
	"for the friend you only see once a year",
	"for chosen family",
	"for former roommates",
	"for neighbors you've never met",
	"for neighbors who became friends",
	"for strangers on the train",
	"for strangers who smiled at you",
	"for the person who held the door",
	"for the person who didn't hold the door",
	"for almost-lovers",
	"for never-lovers",
	"for the one who got away",
	"for the one who stayed",
	"for the one who came back",
	"for unrequited feelings",
	"for requited feelings",
	"for the first date",
	"for the last date",
	"for the date that wasn't a date",
	"for people you miss",
	"for people you don't miss yet",
	"for people you'll never see again",
	"for people you see every day but never talk to",
	"for the group chat",
	"for the dead group chat",
	"for the group chat that never sleeps",

	// ── places ──
	"for the kitchen table",
	"for the front porch",
	"for the fire escape",
	"for the rooftop",
	"for the basement",
	"for the attic",
	"for the closet you hid in as a kid",
	"for the park bench",
	"for the library",
	"for the library after hours",
	"for the bookstore",
	"for the used bookstore",
	"for the coffee shop where they know your order",
	"for the coffee shop where no one knows you",
	"for the diner at 1am",
	"for the bar at closing time",
	"for the hotel room",
	"for the airport terminal",
	"for the departure gate",
	"for the arrivals hall",
	"for hospital waiting rooms",
	"for the hallway outside the office",
	"for the bathroom stall",
	"for the shower",
	"for the bathtub",
	"for the bed you can't leave",
	"for the bed you can't sleep in",
	"for the childhood bedroom",
	"for the apartment you outgrew",
	"for the house you grew up in",
	"for the city you left",
	"for the city you moved to",
	"for the town that never changes",
	"for the place that doesn't exist anymore",
	"for the corner booth",
	"for the window seat",
	"for the middle seat",
	"for the top bunk",
	"for the bottom bunk",
	"for the hammock",
	"for the treehouse",

	// ── feelings & states ──
	"for anxiety",
	"for the absence of anxiety",
	"for the moment before you know",
	"for the moment after you know",
	"for déjà vu",
	"for nostalgia",
	"for nostalgia for things that never happened",
	"for homesickness",
	"for homesickness for a place you've never been",
	"for the feeling you can't name",
	"for the feeling you can name but won't",
	"for butterflies",
	"for gut feelings",
	"for hunches",
	"for premonitions",
	"for hindsight",
	"for foresight",
	"for blindsight",
	"for the ache",
	"for the relief",
	"for the numbness",
	"for the thaw",
	"for rage",
	"for quiet rage",
	"for joy",
	"for quiet joy",
	"for boredom",
	"for productive boredom",
	"for restlessness",
	"for stillness",
	"for loneliness in a crowd",
	"for solitude that isn't lonely",
	"for the sigh",
	"for the deep breath",
	"for the held breath",
	"for the exhale",
	"for the lump in your throat",
	"for the weight on your chest",
	"for the lightness after crying",
	"for happy tears",
	"for angry tears",
	"for tears you didn't expect",
	"for the laugh that comes from nowhere",
	"for the laugh that turns into crying",
	"for the cry that turns into laughing",
	"for second thoughts",
	"for third thoughts",
	"for no thoughts",
	"for intrusive thoughts",
	"for recurring thoughts",
	"for the thought you can't shake",
	"for the thought that woke you up",
	"for the thought that kept you up",

	// ── creation & work ──
	"for side projects",
	"for abandoned side projects",
	"for the side project that became the main thing",
	"for prototypes",
	"for wireframes",
	"for mockups",
	"for sketches",
	"for doodles",
	"for doodles that became logos",
	"for the thing you built in a weekend",
	"for the thing you've been building for years",
	"for the commit message no one will read",
	"for code comments",
	"for TODO comments",
	"for FIXME comments",
	"for HACK comments",
	"for the bug you can't reproduce",
	"for the bug that reproduces every time",
	"for the fix that broke something else",
	"for the refactor",
	"for the rewrite",
	"for the rewrite of the rewrite",
	"for version one",
	"for version two",
	"for version zero",
	"for the beta",
	"for the alpha",
	"for the MVP",
	"for scope creep",
	"for feature requests",
	"for the feature no one asked for",
	"for the feature everyone needed",
	"for shipping",
	"for not shipping",
	"for shipping too early",
	"for shipping too late",
	"for shipping at 2am",
	"for the demo",
	"for the demo that crashed",
	"for the demo that worked perfectly",
	"for presentations",
	"for the slide you skipped",
	"for the Q&A",

	// ── music & art ──
	"for the song on repeat",
	"for the song you can't find",
	"for the song that found you",
	"for the lyric you misheard",
	"for the lyric you got tattooed",
	"for the album that changed everything",
	"for the playlist for no one",
	"for the playlist for someone specific",
	"for the playlist titled 'chill'",
	"for the painting you stared at too long",
	"for the photograph you almost deleted",
	"for the photograph you wish you'd taken",
	"for the film you watched alone",
	"for the film you can't rewatch",
	"for the film you've seen twelve times",
	"for the scene you think about",
	"for the quote you misattribute",
	"for the book that ruined you",
	"for the book that rebuilt you",
	"for the poem you memorized",
	"for the poem you forgot",
	"for the poem you didn't know was a poem",

	// ── food & drink ──
	"for the first sip",
	"for the last sip",
	"for cold coffee",
	"for reheated coffee",
	"for herbal tea at midnight",
	"for the meal you cooked for someone",
	"for the meal no one ate",
	"for the meal that tasted like home",
	"for the recipe passed down",
	"for the recipe you lost",
	"for the recipe you invented",
	"for midnight snacks",
	"for breakfast for dinner",
	"for dinner for breakfast",
	"for the restaurant that closed",
	"for the restaurant you keep meaning to try",
	"for the meal you photographed but didn't eat",
	"for comfort food",
	"for food you pretend to like",
	"for the grocery store at 11pm",

	// ── technology & internet ──
	"for the tab you've had open for weeks",
	"for the bookmark you'll never revisit",
	"for the browser history you cleared",
	"for the password you forgot",
	"for the password that's your ex's birthday",
	"for the email you drafted but never sent",
	"for the email you sent too fast",
	"for the reply-all disaster",
	"for the DM you screenshot",
	"for the DM you didn't screenshot",
	"for the text you typed and deleted",
	"for the text you sent to the wrong person",
	"for the voicemail you never listened to",
	"for the voicemail you saved for years",
	"for the notification you ignored",
	"for the notification that changed your day",
	"for the phone call you avoided",
	"for the phone call you wish you'd answered",
	"for the app you deleted",
	"for the app you redownloaded",
	"for screen time reports",
	"for do not disturb",
	"for airplane mode",
	"for the dead battery",
	"for the charger you forgot",
	"for the WiFi password",

	// ── body & health ──
	"for the deep stretch",
	"for the cracked knuckle",
	"for the held breath before jumping",
	"for the cold plunge",
	"for the hot shower",
	"for the nap that fixed everything",
	"for the nap that made it worse",
	"for the walk that cleared your head",
	"for the run that didn't",
	"for the gym at 6am",
	"for the gym at midnight",
	"for the gym membership you forgot about",
	"for people who tried yoga once",
	"for the meditation that lasted thirty seconds",
	"for the headache",
	"for the thing you should see a doctor about",

	// ── memory & time ──
	"for the thing you remember wrong",
	"for the thing only you remember",
	"for the thing everyone remembers differently",
	"for the photograph that doesn't match your memory",
	"for the smell that brought it all back",
	"for the song that brought it all back",
	"for the street that brought it all back",
	"for the taste that brought it all back",
	"for the voice you're forgetting",
	"for the face you're forgetting",
	"for the name you forgot mid-sentence",
	"for the dream you can't remember",
	"for the dream you can't forget",
	"for the dream that felt real",
	"for the reality that felt like a dream",
	"for lucid dreams",
	"for nightmares",
	"for recurring dreams",
	"for daydreams",
	"for the future you imagined at fifteen",
	"for the future you imagine now",
	"for the past you romanticize",
	"for the past you can't romanticize",
	"for the present",
	"for right now",

	// ── nature ──
	"for the ocean",
	"for the mountain",
	"for the desert",
	"for the forest",
	"for the river",
	"for the lake at dawn",
	"for the field at dusk",
	"for the garden you neglected",
	"for the garden that grew anyway",
	"for wildflowers",
	"for weeds",
	"for the tree you climbed as a kid",
	"for the tree that's no longer there",
	"for the sunset you didn't photograph",
	"for the sunrise you almost missed",
	"for the stars you can't see from the city",
	"for the stars you drove an hour to see",
	"for the moon through the window",
	"for thunder",
	"for the first rain after a drought",
	"for puddles",
	"for the crack in the sidewalk",
	"for the dandelion in the crack",

	// ── identity & becoming ──
	"for the person you were",
	"for the person you are",
	"for the person you're becoming",
	"for the person you pretend to be",
	"for the person you are when no one's watching",
	"for the mask",
	"for the moment you took it off",
	"for the version of you that exists in other people's stories",
	"for the version of you that exists in your own",
	"for reinvention",
	"for the quarter-life crisis",
	"for the mid-life crisis",
	"for the crisis that wasn't a crisis",
	"for the pivot",
	"for the leap",
	"for the landing",
	"for the fall",
	"for getting back up",
	"for staying down a little longer",
	"for the growth you can't see",
	"for the growth everyone else can see",
	"for the thing you outgrew",
	"for the thing you grew into",
	"for the name you chose",
	"for the name you were given",
	"for the nickname",
	"for the inside joke",
	"for the inside joke no one else gets",

	// ── philosophy & wonder ──
	"for questions without answers",
	"for answers without questions",
	"for the meaning of life",
	"for the meaning of Tuesday",
	"for the meaning of the dream",
	"for coincidences",
	"for patterns",
	"for the pattern you're imagining",
	"for free will",
	"for fate",
	"for the argument for both",
	"for the unknowable",
	"for the almost knowable",
	"for the obvious thing you missed",
	"for the thing hiding in plain sight",
	"for paradoxes",
	"for contradictions",
	"for the contradiction you are",
	"for nuance",
	"for the grey area",
	"for the binary you rejected",
	"for the spectrum",
	"for infinity",
	"for the finite",
	"for the edge of the map",
	"for what's past the edge",
	"for the question you're afraid to ask",
	"for the answer you're afraid to hear",
	"for the silence after the question",
	"for the silence that says everything",

	// ── everyday life ──
	"for the commute",
	"for the shortcut through the alley",
	"for the elevator conversation",
	"for the elevator silence",
	"for holding the elevator",
	"for taking the stairs",
	"for the junk drawer",
	"for the thing in the junk drawer you might need someday",
	"for the closet you haven't cleaned",
	"for the box you haven't unpacked",
	"for the box from two moves ago",
	"for laundry day",
	"for the clothes that don't fit",
	"for the clothes you keep anyway",
	"for the outfit you wore on the best day",
	"for the umbrella you forgot",
	"for the umbrella you lent and never got back",
	"for keys you can't find",
	"for the spare key under the mat",
	"for the door you left unlocked",
	"for the light you left on",
	"for the window you left open",
	"for the alarm you slept through",
	"for the alarm you set but didn't need",
	"for the snooze button",
	"for the five more minutes",
	"for the ten more minutes",
	"for the whole extra hour",

	// ── communication ──
	"for the conversation you rehearsed",
	"for the conversation that went nothing like you rehearsed",
	"for the thing you said",
	"for the thing you didn't say",
	"for the thing you should have said",
	"for the thing you wish you hadn't said",
	"for the perfect comeback three hours later",
	"for the apology",
	"for the apology you're owed",
	"for the apology you owe",
	"for the thank you",
	"for the thank you that came too late",
	"for the goodbye",
	"for the goodbye you didn't get",
	"for the hello you weren't expecting",
	"for small talk",
	"for the small talk that became deep talk",
	"for the deep talk at the wrong time",
	"for the silence between old friends",
	"for the silence between strangers",
	"for the nod",
	"for the wave",
	"for the awkward wave",
	"for the hug that lasted too long",
	"for the hug that didn't last long enough",
	"for the handshake",
	"for the fist bump",

	// ── ambition & failure ──
	"for the thing you almost did",
	"for the thing you actually did",
	"for the thing you'll do tomorrow",
	"for the thing you said you'd do yesterday",
	"for the risk",
	"for the calculated risk",
	"for the reckless risk",
	"for the safe choice",
	"for the safe choice you regret",
	"for the dangerous choice you don't",
	"for the failure",
	"for the spectacular failure",
	"for the quiet failure",
	"for the failure no one noticed",
	"for the success no one noticed",
	"for the success that felt like failure",
	"for the failure that felt like success",
	"for the lesson",
	"for the lesson you had to learn twice",
	"for the lesson you had to learn three times",
	"for the lesson you still haven't learned",
	"for persistence",
	"for stubbornness",
	"for knowing the difference",
	"for giving up",
	"for giving up gracefully",
	"for starting over",
	"for starting over again",
	"for the blank slate",
	"for the clean install",
	"for the fresh start that wasn't",

	// ── objects & things ──
	"for the thing you lost",
	"for the thing you found",
	"for the thing you found while looking for something else",
	"for the thing you kept for no reason",
	"for the thing you threw away and wanted back",
	"for the box of old photographs",
	"for the letter in the drawer",
	"for the ticket stub",
	"for the receipt from that night",
	"for the mix CD",
	"for the playlist that replaced the mix CD",
	"for the book with the folded corner",
	"for the book with someone else's notes",
	"for the pen that ran out of ink",
	"for the pen you borrowed and kept",
	"for the mug with the chip",
	"for the mug from the place you visited once",
	"for the shirt you stole",
	"for the hoodie you'll never return",
	"for the thing on your desk you can't explain",

	// ── seasons of life ──
	"for the first day",
	"for the last day",
	"for the first day at the new place",
	"for the last day at the old place",
	"for moving day",
	"for the empty apartment",
	"for the full apartment",
	"for the first night in a new city",
	"for the last night in the old one",
	"for graduation",
	"for the day after graduation",
	"for the job you quit",
	"for the job you got fired from",
	"for the job you loved",
	"for the job you tolerated",
	"for retirement",
	"for the retirement you're not planning",
	"for the wedding",
	"for the divorce",
	"for the baby",
	"for the empty nest",
	"for the reunion",
	"for the funeral",
	"for the birthday you dreaded",
	"for the birthday that surprised you",
	"for the age you thought was old",
	"for the age you are now",

	// ── meta & self-reference ──
	"for the thing you're writing right now",
	"for the thing you're about to write",
	"for the thing you just deleted",
	"for the thing you'll never publish",
	"for the thing you published too soon",
	"for the thing you're not ready to write",
	"for the thing that wrote itself",
	"for the writing about writing",
	"for the procrastination",
	"for the productive procrastination",
	"for the deadline",
	"for the missed deadline",
	"for the self-imposed deadline",
	"for the draft in your head",
	"for the draft on your phone",
	"for the draft in your notes app",
	"for the notes app",
	"for the voice memo",
	"for the voice memo you can't understand",
	"for the screenshot you forgot why you took",
	"for the bookmark folder called 'read later'",
	"for 'read later'",
	"for 'I'll remember this'",
	"for 'I should write this down'",
	"for writing it down",
	"for finally writing it down",

	// ── sounds ──
	"for the sound of rain on the window",
	"for the sound of typing",
	"for the sound of a pen on paper",
	"for the sound of pages turning",
	"for the creak of the door",
	"for the click of the lock",
	"for the hum of the refrigerator",
	"for the song from the other room",
	"for the conversation through the wall",
	"for the siren in the distance",
	"for the bird at 5am",
	"for the wind",
	"for the silence after the music stops",

	// ── digital life ──
	"for the profile you curated",
	"for the profile that's nothing like you",
	"for the bio you keep changing",
	"for the avatar",
	"for the username you've had since you were thirteen",
	"for the draft in your notes app at 3am",
	"for the photo dump",
	"for the finsta",
	"for the account with zero followers",
	"for the tweet you deleted",
	"for the post you archived",
	"for the post that got zero likes",
	"for the post that got too many likes",
	"for the comment you almost left",
	"for the comment section",
	"for the unsubscribe",
	"for the mute button",
	"for the block button",
	"for the unblock",

	// ── quiet moments ──
	"for the pause",
	"for the breath between sentences",
	"for the space between words",
	"for the gap between thoughts",
	"for the moment before you speak",
	"for the moment after you speak",
	"for the walk without headphones",
	"for the drive without the radio",
	"for the meal without your phone",
	"for the afternoon without plans",
	"for the evening without screens",
	"for the morning without alarms",
	"for the weekend with nothing to do",
	"for the weekend with too much to do",
	"for doing nothing",
	"for doing nothing on purpose",
	"for sitting with it",
	"for letting it go",
	"for not letting it go yet",
	"for holding on",
	"for holding on a little longer",

	// ── language & translation ──
	"for the word that doesn't translate",
	"for the language you're forgetting",
	"for the language you're learning",
	"for the accent you lost",
	"for the accent you picked up",
	"for the phrase your grandmother used",
	"for the idiom that makes no sense",
	"for the idiom that makes perfect sense",
	"for thinking in two languages",
	"for dreaming in a different language",
	"for the subtitle you misread",
	"for the sign you couldn't read",
	"for the menu you pointed at",

	// ── childhood ──
	"for the imaginary friend",
	"for the monster under the bed",
	"for the night light",
	"for the bedtime story",
	"for the lullaby",
	"for the playground",
	"for the swing set",
	"for the sandbox",
	"for the fort made of blankets",
	"for the fort made of couch cushions",
	"for the hiding spot no one found",
	"for the hiding spot everyone knew about",
	"for the crayon drawing on the wall",
	"for the gold star",
	"for the participation trophy",
	"for the report card",
	"for the snow day",
	"for the field trip",
	"for the bus ride home",
	"for the lunch table",
	"for the cafeteria",
	"for recess",
	"for the game you invented",
	"for the rules you made up",
	"for the rules you broke",

	// ── money & survival ──
	"for the rent check",
	"for the overdraft",
	"for the tip you couldn't afford",
	"for the tip you left anyway",
	"for the thing you saved up for",
	"for the thing you bought on impulse",
	"for the thing you returned",
	"for the thing you couldn't return",
	"for the budget spreadsheet",
	"for the budget you abandoned",
	"for the raise you asked for",
	"for the raise you didn't get",
	"for the side hustle",
	"for the side hustle that became the hustle",
	"for free trials",
	"for subscriptions you forgot about",

	// ── movement & travel ──
	"for the road trip",
	"for the wrong turn",
	"for the U-turn",
	"for the dead end",
	"for the roundabout",
	"for the rest stop",
	"for the gas station at midnight",
	"for the map you didn't need",
	"for the map you needed",
	"for getting lost",
	"for getting lost on purpose",
	"for the place you found by accident",
	"for the postcard you never sent",
	"for the souvenir you regret",
	"for the souvenir you treasure",
	"for the passport stamp",
	"for the visa denial",
	"for the border crossing",
	"for the connecting flight",
	"for the missed connection",
	"for the turbulence",

	// ── animals ──
	"for the stray you fed",
	"for the stray that followed you home",
	"for the pet you grew up with",
	"for the pet you lost",
	"for the pet you talk to like a person",
	"for the squirrel outside the window",
	"for the spider you didn't kill",
	"for the spider you killed and felt bad about",
	"for the bird that won't shut up",
	"for the bird that sings just for you",
	"for the fish tank",
	"for the ant trail",

	// ── seasons & weather ──
	"for the first snowfall",
	"for the last snowfall",
	"for the ice on the windshield",
	"for the heat wave",
	"for the power outage",
	"for the candle during the power outage",
	"for the tornado warning",
	"for the false alarm",
	"for the rainbow you almost missed",
	"for the double rainbow",
	"for the humidity",
	"for the dry heat",
	"for the perfect temperature",
	"for the breeze through the window",
	"for the window you can't open",

	// ── rituals & habits ──
	"for the morning routine",
	"for the night routine",
	"for the routine you abandoned",
	"for the routine you can't live without",
	"for the habit you're building",
	"for the habit you're breaking",
	"for the habit you don't notice",
	"for the superstition",
	"for the lucky charm",
	"for the knock on wood",
	"for the wish on the eyelash",
	"for the wish on the dandelion",
	"for the wish on 11:11",
	"for the birthday wish",
	"for the wish you won't say out loud",
	"for the coin in the fountain",
	"for the crossed fingers",
	"for the deep breath before you start",

	// ── miscellaneous ──
	"for the thing you googled at 3am",
	"for the Wikipedia rabbit hole",
	"for the conspiracy theory you half believe",
	"for the documentary that changed you",
	"for the podcast you recommend to everyone",
	"for the podcast no one listens to",
	"for the argument you won in your head",
	"for the argument you lost in real life",
	"for the apology you rehearsed in the shower",
	"for the compliment you didn't believe",
	"for the compliment you still think about",
	"for the outfit no one complimented",
	"for the haircut",
	"for the bad haircut",
	"for the haircut that changed everything",
	"for the mirror",
	"for the mirror you avoided",
	"for the photo you hate",
	"for the photo you love",
	"for the photo that looks nothing like you",
	"for the scar",
	"for the scar with the story",
	"for the tattoo you want",
	"for the tattoo you regret",
	"for the tattoo that's perfect",
	"for the piercing that closed",
	"for the tan line",
	"for the sunburn",
	"for the freckle",
	"for the wrinkle you earned",

	// ── closing ──
	"for the end",
	"for the beginning",
	"for the middle",
	"for the part you're in right now",
	"for what comes next",
	"for what came before",
	"for the thing after the thing",
	"for one more line",
	"for the last word",
	"for the words that haven't been written",
	"for the blank space after the period",
	"for tomorrow",
	"for today",
	"for this",
];

export default FOR_LINES;

const FOR_LINES_COUNT = 150;

export function getRandomForLines(): string[] {
	const shuffled = [...FOR_LINES];
	// Fisher-Yates shuffle
	for (let i = shuffled.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
	}
	return shuffled.slice(0, FOR_LINES_COUNT);
}
