version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: writer-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - writer-pg-data:/var/lib/postgresql/data

volumes:
  writer-pg-data:
